# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ing_Dni.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtWidgets import QApplication, QDialog
from PyQt5.QtCore import pyqtSlot
import funciones


#Pantalla de ingreso de DNI_PUERTA
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        # Función para manejar el evento del botón de entrada
        @pyqtSlot()
        def on_B_entrada_clicked():
            dni = self.lineEdit.text()
            return funciones.dni_control(dni)

        Dialog.setObjectName("Dialog")
        Dialog.resize(315, 258)
        Dialog.setStyleSheet("/* Resetear estilos por defecto */\n"
            "* {\n"
            "  margin: 0;\n"
            "  padding: 0;\n"
            "  border: none;\n"
            "  outline: none;\n"
            "  font-family: Arial, sans-serif;\n"
            "}\n"
            "\n"
            "/* Estilo de la ventana principal */\n"
            "QDialog {\n"
            "  background-color:#F4F2F2;\n"
            "}\n"
            "\n"
            "/* Estilo del boton de entrada*/\n"
            "QPushButton {\n"
            "  background-color: #246EC7;\n"
            "  color: #ffffff;\n"
            "  border-radius: 5px;\n"
            "}\n"
            "\n"
            "/*Estilo del boton de salida*/\n"
            "#B_salida {\n"
            "  background-color: #C73224;\n"
            "  color: #ffffff;\n"
            " /* padding: 10px 20px;*/\n"
            "  border-radius: 5px;\n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "  background-color: #27ae60;\n"
            "}\n"
            "\n"
            "/* Estilo de las etiquetas de texto titulo*/\n"
            "QLabel {\n"
            "  color: #000000;\n"
            "  font-size: 16px;\n"
            "  font-weight: bold;\n"
            "}\n"
            "/* Estilo de las etiquetas de texto titulo_dni*/\n"
            "#Titulo_Dni {\n"
            "  color: #547A78;\n"
            "  font-size: 14px;\n"
            "}\n"
            "/* Estilo de los campos de entrada de texto */\n"
            "QLineEdit {\n"
            "  padding: 0px;\n"
            "  border: 1px solid #cccccc;\n"
            "  border-radius: 5px;\n"
            "}\n"
            "\n"
            "/* Estilo de las áreas de texto */\n"
            "QTextEdit {\n"
            "  padding: 5px;\n"
            "  border: 1px solid #cccccc;\n"
            "  border-radius: 3px;\n"
            "}\n"
            "\n"
            "/* Estilo de las barras de desplazamiento */\n"
            "QScrollBar:vertical {\n"
            "  width: 8px;\n"
            "}\n"
            "\n"
            "QScrollBar:horizontal {\n"
            "  height: 8px;\n"
            "}\n"
            "\n"
            "QScrollBar::handle {\n"
            "  background-color: #cccccc;\n"
            "  border-radius: 4px;\n"
            "}\n"
            "\n"
            "QScrollBar::handle:hover {\n"
            "  background-color: #999999;\n"
            "}\n"
            "\n"
            "QScrollBar::add-page, QScrollBar::sub-page {\n"
            "  background: none;\n"
            "}\n"
            "\n"
            "QScrollBar::add-line, QScrollBar::sub-line {\n"
            "  background: none;\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:vertical {\n"
            "  height: 0px;\n"
            "}\n"
            "\n"
            "QScrollBar::sub-line:vertical {\n"
            "  height: 0px;\n"
            "}\n"
            "\n"
            "QScrollBar::add-line:horizontal {\n"
            "  width: 0px;\n"
            "}\n"
            "\n"
            "QScrollBar::sub-line:horizontal {\n"
            "  width: 0px;\n"
            "}\n"
            "\n"
            "")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(50, 130, 221, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.Titulo = QtWidgets.QLabel(Dialog)
        self.Titulo.setGeometry(QtCore.QRect(20, 40, 271, 21))
        self.Titulo.setObjectName("Titulo")
        self.Titulo_Dni = QtWidgets.QLabel(Dialog)
        self.Titulo_Dni.setGeometry(QtCore.QRect(50, 110, 31, 16))
        self.Titulo_Dni.setObjectName("Titulo_Dni")
        self.B_entrada = QtWidgets.QPushButton(Dialog)
        self.B_entrada.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.B_entrada.setObjectName("B_entrada")
        self.B_entrada.clicked.connect(on_B_entrada_clicked)
        self.B_salida = QtWidgets.QPushButton(Dialog)
        self.B_salida.setGeometry(QtCore.QRect(190, 190, 75, 23))
        self.B_salida.setObjectName("B_salida")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Titulo.setText(_translate("Dialog", "INGRESE LOS DATOS SOLICITADOS "))
        self.Titulo_Dni.setText(_translate("Dialog", "DNI:"))
        self.B_entrada.setText(_translate("Dialog", "ENTRADA"))
        self.B_salida.setText(_translate("Dialog", "SALIDA"))
    
def abrir_dialogo2():
    dialogo2 = Ui_Dialog1Dni()
    Ui_Dialog.close()
    dialogo2.exec()


#Pantalla de ingreso de CARGA_FLETERO_PUERTA
class Ui_Dialog1Dni(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 561)
        Dialog.setStyleSheet("/* Resetear estilos por defecto */\n"
        "* {\n"
        "  margin: 0;\n"
        "  padding: 0;\n"
        "  border: none;\n"
        "  outline: none;\n"
        "  font-family: Arial, sans-serif;\n"
        "}\n"
        "\n"
        "/* Estilo de la ventana principal */\n"
        "QDialog {\n"
        "  background-color:#F4F2F2;\n"
        "}\n"
        "\n"
        "/* Estilo del boton de entrada*/\n"
        "QPushButton {\n"
        "  background-color: #246EC7;\n"
        "  color: #ffffff;\n"
        "  border-radius: 5px;\n"
        "}\n"
        "\n"
        "/*Estilo del boton de salida*/\n"
        "#B_salida {\n"
        "  background-color: #C73224;\n"
        "  color: #ffffff;\n"
        " /* padding: 10px 20px;*/\n"
        "  border-radius: 5px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "  background-color: #27ae60;\n"
        "}\n"
        "\n"
        "/* Estilo de las etiquetas de texto titulo*/\n"
        "QLabel {\n"
        "  color: #000000;\n"
        "  font-size: 20px;\n"
        "  font-weight: bold;\n"
        "}\n"
        "/* Estilo de las etiquetas de texto titulo_dni*/\n"
        "#SubTitulo {\n"
        "  color: #547A78;\n"
        "  font-size: 14px;\n"
        "}\n"
        "\n"
        "#SubTitulo_2 {\n"
        "  color: #547A78;\n"
        "  font-size: 14px;\n"
        "}\n"
        "\n"
        "#SubTitulo_3 {\n"
        "  color: #547A78;\n"
        "  font-size: 14px;\n"
        "}\n"
        "/* Estilo de los campos de entrada de texto */\n"
        "QLineEdit {\n"
        "  padding: 0px;\n"
        "  border: 1px solid #cccccc;\n"
        "  border-radius: 5px;\n"
        "}\n"
        "\n"
        "/* Estilo de las áreas de texto */\n"
        "QTextEdit {\n"
        "  padding: 5px;\n"
        "  border: 1px solid #cccccc;\n"
        "  border-radius: 3px;\n"
        "}\n"
        "\n"
        "/* Estilo de las barras de desplazamiento */\n"
        "QScrollBar:vertical {\n"
        "  width: 8px;\n"
        "}\n"
        "\n"
        "QScrollBar:horizontal {\n"
        "  height: 8px;\n"
        "}\n"
        "\n"
        "QScrollBar::handle {\n"
        "  background-color: #cccccc;\n"
        "  border-radius: 4px;\n"
        "}\n"
        "\n"
        "QScrollBar::handle:hover {\n"
        "  background-color: #999999;\n"
        "}\n"
        "\n"
        "QScrollBar::add-page, QScrollBar::sub-page {\n"
        "  background: none;\n"
        "}\n"
        "\n"
        "QScrollBar::add-line, QScrollBar::sub-line {\n"
        "  background: none;\n"
        "}\n"
        "\n"
        "QScrollBar::add-line:vertical {\n"
        "  height: 0px;\n"
        "}\n"
        "\n"
        "QScrollBar::sub-line:vertical {\n"
        "  height: 0px;\n"
        "}\n"
        "\n"
        "QScrollBar::add-line:horizontal {\n"
        "  width: 0px;\n"
        "}\n"
        "\n"
        "QScrollBar::sub-line:horizontal {\n"
        "  width: 0px;\n"
        "}\n"
        "\n"
        "")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 470, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 470, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 371, 31))
        self.label.setObjectName("label")
        self.SubTitulo_2 = QtWidgets.QLabel(Dialog)
        self.SubTitulo_2.setGeometry(QtCore.QRect(100, 70, 281, 31))
        self.SubTitulo_2.setObjectName("SubTitulo_2")
        self.SubTitulo = QtWidgets.QLabel(Dialog)
        self.SubTitulo.setGeometry(QtCore.QRect(100, 160, 281, 31))
        self.SubTitulo.setObjectName("SubTitulo")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 100, 231, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 190, 231, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(130, 270, 181, 171))
        self.graphicsView.setObjectName("graphicsView")
        self.SubTitulo_3 = QtWidgets.QLabel(Dialog)
        self.SubTitulo_3.setGeometry(QtCore.QRect(100, 240, 281, 31))
        self.SubTitulo_3.setObjectName("SubTitulo_3")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 270, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 310, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "INGRESAR"))
        self.pushButton_2.setText(_translate("Dialog", "CANCELAR"))
        self.label.setText(_translate("Dialog", "Formulario de ingreso de nuevo fletero "))
        self.SubTitulo_2.setText(_translate("Dialog", "Nombre:"))
        self.SubTitulo.setText(_translate("Dialog", "Apellido:"))
        self.SubTitulo_3.setText(_translate("Dialog", "Foto:"))
        self.pushButton_3.setText(_translate("Dialog", "TOMAR"))
        self.pushButton_4.setText(_translate("Dialog", "REPETIR"))

if __name__ == "__main__":
    # Crear una instancia de la aplicación
    app = QApplication(sys.argv)

    # Crear una instancia del diálogo
    dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(dialog)

    # Mostrar el diálogo
    dialog.show()

    # Ejecutar la aplicación
    sys.exit(app.exec_())