    # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ing_Dni.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyodbc
'''import Funciones'''

#1-Pantalla validar dni
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(315, 258)
        Dialog.setStyleSheet("/* Resetear estilos por defecto */\n"
        "* {\n"
        "  margin: 0;\n"
        "  padding: 0;\n"
        "  border: none;\n"
        "  outline: none;\n"
        "  font-family: Arial, sans-serif;\n"
        "}\n"
        "\n"
        "/* Estilo de la ventana principal */\n"
        "QDialog {\n"
        "  background-color:#F4F2F2;\n"
        "}\n"
        "\n"
        "/* Estilo del boton de entrada*/\n"
        "QPushButton {\n"
        "  background-color: #246EC7;\n"
        "  color: #ffffff;\n"
        "  border-radius: 5px;\n"
        "}\n"
        "\n"
        "/*Estilo del boton de salida*/\n"
        "#B_salida {\n"
        "  background-color: #C73224;\n"
        "  color: #ffffff;\n"
        " /* padding: 10px 20px;*/\n"
        "  border-radius: 5px;\n"
        "}\n"
        "\n"
        "QPushButton:hover {\n"
        "  background-color: #27ae60;\n"
        "}\n"
        "\n"
        "/* Estilo de las etiquetas de texto titulo*/\n"
        "QLabel {\n"
        "  color: #000000;\n"
        "  font-size: 16px;\n"
        "  font-weight: bold;\n"
        "}\n"
        "/* Estilo de las etiquetas de texto titulo_dni*/\n"
        "#Titulo_Dni {\n"
        "  color: #547A78;\n"
        "  font-size: 14px;\n"
        "}\n"
        "/* Estilo de los campos de entrada de texto */\n"
        "QLineEdit {\n"
        "  padding: 0px;\n"
        "  border: 1px solid #cccccc;\n"
        "  border-radius: 5px;\n"
        "}\n"
        "\n"
        "/* Estilo de las áreas de texto */\n"
        "QTextEdit {\n"
        "  padding: 5px;\n"
        "  border: 1px solid #cccccc;\n"
        "  border-radius: 3px;\n"
        "}\n"
        "\n"
        "/* Estilo de las barras de desplazamiento */\n"
        "QScrollBar:vertical {\n"
        "  width: 8px;\n"
        "}\n"
        "\n"
        "QScrollBar:horizontal {\n"
        "  height: 8px;\n"
        "}\n"
        "\n"
        "QScrollBar::handle {\n"
        "  background-color: #cccccc;\n"
        "  border-radius: 4px;\n"
        "}\n"
        "\n"
        "QScrollBar::handle:hover {\n"
        "  background-color: #999999;\n"
        "}\n"
        "\n"
        "QScrollBar::add-page, QScrollBar::sub-page {\n"
        "  background: none;\n"
        "}\n"
        "\n"
        "QScrollBar::add-line, QScrollBar::sub-line {\n"
        "  background: none;\n"
        "}\n"
        "\n"
        "QScrollBar::add-line:vertical {\n"
        "  height: 0px;\n"
        "}\n"
        "\n"
        "QScrollBar::sub-line:vertical {\n"
        "  height: 0px;\n"
        "}\n"
        "\n"
        "QScrollBar::add-line:horizontal {\n"
        "  width: 0px;\n"
        "}\n"
        "\n"
        "QScrollBar::sub-line:horizontal {\n"
        "  width: 0px;\n"
        "}\n"
        "\n"
        "")

         # Función para manejar el evento del botón de entrada
        @QtCore.pyqtSlot()
        def on_B_entrada_clicked():
            global dni
            dni = self.lineEdit.text()
            dni_control(dni,Dialog)  # Llamar a la función en el archivo funciones.py

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(50, 130, 221, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.Titulo = QtWidgets.QLabel(Dialog)
        self.Titulo.setGeometry(QtCore.QRect(20, 40, 271, 21))
        self.Titulo.setObjectName("Titulo")
        self.Titulo_Dni = QtWidgets.QLabel(Dialog)
        self.Titulo_Dni.setGeometry(QtCore.QRect(50, 110, 31, 16))
        self.Titulo_Dni.setObjectName("Titulo_Dni")
        self.B_entrada = QtWidgets.QPushButton(Dialog)
        self.B_entrada.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.B_entrada.setObjectName("B_entrada")
        self.B_entrada.clicked.connect(on_B_entrada_clicked)
        self.B_salida = QtWidgets.QPushButton(Dialog)
        self.B_salida.setGeometry(QtCore.QRect(190, 190, 75, 23))
        self.B_salida.setObjectName("B_salida")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Titulo.setText(_translate("Dialog", "INGRESE LOS DATOS SOLICITADOS "))
        self.Titulo_Dni.setText(_translate("Dialog", "DNI:"))
        self.B_entrada.setText(_translate("Dialog", "ENTRADA"))
        self.B_salida.setText(_translate("Dialog", "SALIDA"))

#1.a-Logica validar Pantalla anteior 
def dni_control(dni,Dialog):
    try:
        # Establecer la conexión a la base de datos
        connection = pyodbc.connect('Driver={SQL Server};Server=DESKTOP-8AO7HCU;Database=CONTROL_VEIHCULAR;uid=sa;pwd=kncb0405')

        cursor = connection.cursor()
        cursor.execute("SELECT dni_fletero FROM fletero WHERE dni_fletero = ?", dni)
        results = cursor.fetchall()

        if not results:
            print("DNI " + dni + " inexistente en el sistema")
            cursor.close()
            return abrir_dialogo2(Dialog)#dni_carga(dni)
        else:
            cursor.close()
            print("El DNI " + dni + " se encuentra dado de alta")
            return 1 #patente_control(patente=input("Ingrese patente de vehículo: "))
        

    except Exception as e:
        print("Error en la consulta de validación de DNI:", e)
'''----------------------------------------------------------------------------------------------------------------'''
#Inicio del modulo puro
app = QtWidgets.QApplication([])
dialog = QtWidgets.QDialog()
ui = Ui_Dialog()
ui.setupUi(dialog)
dialog.show()


def abrir_dialogo2 (Dialog):
    import Alta_Fletero_Pantalla
    Dialog.close()
    '''En este código, se crea una nueva instancia de la clase QDialog llamada dialog. Luego, se instancia la clase Ui_Dialog y se llama al método setupUi() pasando dialog como argumento para configurar la interfaz gráfica del diálogo. Finalmente, se llama al método exec_() en dialog para mostrar el diálogo y esperar hasta que el usuario lo cierre.'''
    dialog = QtWidgets.QDialog()
    ui = Alta_Fletero_Pantalla.Ui_Dialog()
    ui.setupUi(dialog)
    dialog.exec_()

   
 

app.exec_()
